# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run python application

on:
  schedule:
    - cron: '*/1 * * * *' # Schedule to run every minute, regardless of push

permissions:
  contents: read

jobs:
  run_iss_tracker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
      with:
        node-version: ${{ matrix.node_version }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi
    - name: Check then run ISS tracker
      run: | 
        if [ -f "scripts/iss_tracker.py" ]; then 
          echo "iss_tracker.py found"; 
          python3 scripts/iss_tracker.py
        else 
          echo "iss_tracker.py not found"; 
        fi
