# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run python application

on:
  schedule:
    - cron: '*/1 * * * *' # Schedule to run every minute, regardless of push

permissions:
  contents: read

jobs:
  run_iss_tracker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f script/requirements.txt ]; then pip install -r scripts/requirements.txt; fi
    - name: Check installed packages
      run: |
        pip list > scripts/installed_packages.txt
        if grep -Fxq -f scripts/requirements.txt scripts/installed_packages.txt
        then
          echo "All required packages were installed."
        else
          echo "Some required packages were not installed."
          exit 1
        fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check then run ISS tracker
      run: | 
        if [ -f "scripts/iss_tracker.py" ]; then 
          echo "iss_tracker.py found"; 
          python3 scripts/iss_tracker.py
        else 
          echo "iss_tracker.py not found"; 
        fi