name: Run every 5 seconds
on:
  schedule:
    - cron: '*/5 * * * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          while true; do
            python iss_tracker.py
            sleep 5
          done
