name: Python Script Output

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every 10 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script and save output as image
      run: |
        python3 iss_tracker.py
        convert output.png -resize 1000x1000 output_small.png
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output_small.png
