name: Rerun Script Every Minute

on:
  schedule:
    - cron: '*/1 * * * *' # Schedule to run every minute, regardless of push

jobs:
  run_iss_tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run ISS tracker
        run: python3 scripts/iss_tracker.py

      - name: Save output image
        uses: actions/upload-artifact@v2
        with:
          name: iss-tracker-image
          path: output.png
