name: Scheduled re-run

on:
  schedule:
    - cron: '*/1 * * * *' # Schedule to run every minute, regardless of push

jobs:
  run_iss_tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Carbon headers
        run: |
          python -m pip install --upgrade pip
          pip install -y libcairo2-dev libjpeg-dev libgif-dev
          pip install pyobjc-framework-Cocoa==6.0.1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "scripts/requirements.txt" ]; then 
            echo "requirements.txt found"; 
            pip install -r scripts/requirements.txt
          else 
            echo "requirements.txt not found"; 
          fi

      - name: Check then run ISS tracker
        run: | 
          if [ -f "scripts/iss_tracker.py" ]; then 
            echo "iss_tracker.py found"; 
            python3 scripts/iss_tracker.py
          else 
            echo "iss_tracker.py not found"; 
          fi
          

      - name: Save output image
        uses: actions/upload-artifact@v2
        with:
          name: iss-tracker-image
          path: output.png
